code/timothy/django/lab01/grocerylist/urls.py
from django.urls import path
from . import views

app_name = 'grocerylist'

urlpatterns = [
    path('', views.index, name='index'),
    path('complete/<int:grocery_item_id>/', views.complete, name='complete'),
    path('delete/<int:grocery_item_id>/', views.delete, name='delete'),
    path('create/', views.create, name='create'),
    # path('<int:grocery_item_id>/update', views.update, name='update'),
]

code/timothy/django/lab01/grocerylist_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grocerylist/', include('grocerylist.urls')),
]

code/timothy/django/lab01/grocerylist/models.py
from django.db import models

class GroceryItem(models.Model):

    description = models.CharField(max_length=255)

    date_created = models.DateTimeField(verbose_name= 'created', auto_now_add=True)

    date_completed = models.DateTimeField(verbose_name= 'completed', null=True, blank=True)

    is_done = models.BooleanField(verbose_name= 'is complete', default=False)

    def __str__(self):
        return self.description

code/timothy/django/lab01/grocerylist/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import GroceryItem

def index(request):
    latest_grocerylist = GroceryItem.objects.order_by('-date_created')
    not_complete = latest_grocerylist.filter(is_done = False)
    complete = latest_grocerylist.filter(is_done = True)
    # grocery_item = get_object_or_404(GroceryItem, pk=grocery_item.id)
    context = {
        'latest_grocerylist': latest_grocerylist,
        'not_complete': not_complete,
        'complete': complete,
        # 'grocery_item':grocery_item,
    }
    return render(request, 'grocerylist/index.html', context)

def create(request):
    GroceryItem(description = request.POST['description']).save()
    return HttpResponseRedirect(reverse('grocerylist:index'))

def complete(request, grocery_item_id):
    # if request.method == 'post':
    print(grocery_item_id)
    grocery_item = get_object_or_404(GroceryItem, pk=grocery_item_id)
    if grocery_item.is_done == False:
        grocery_item.is_done = True
    else: 
        grocery_item.is_done = False
    grocery_item.save()
    return HttpResponseRedirect(reverse('grocerylist:index'))

def delete(request, grocery_item_id):
    grocery_item = get_object_or_404(GroceryItem, pk=grocery_item_id)
    if request.method == "POST":
        grocery_item.delete()
    return HttpResponseRedirect(reverse('grocerylist:index'))

code/timothy/django/lab01/grocerylist/templates/grocerylist/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grocery List</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'grocerylist/main.css' %}">
</head>
<body>
    <div class="title">
        <h1>Grocery List</h1>
    </div>
    <section>
        <div class="list">
            
            <h3>Items</h3>

            <ul>
                {% for grocery_item in not_complete %}
                    <li>{{ grocery_item }}</li>
                    <form action="{% url 'grocerylist:complete' grocery_item.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Mark Complete">
                    </form>
                    <form action="{% url 'grocerylist:delete' grocery_item.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Delete">
                    </form>
                {% endfor %}
            </ul>
        
        </div>
        <hr>
        <div>
            <h3>Complete</h3>
                
            <ul class="complete">
                {% for grocery_item in complete %}
                    <li>{{ grocery_item }}</li>
                    <form action="{% url 'grocerylist:complete' grocery_item.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Mark Incomplete">
                    </form>
                    <form action="{% url 'grocerylist:delete' grocery_item.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Delete">
                    </form>
                {% endfor %}
            </ul>
        </div>
        <hr>
        <div class="newitem">

            <h3>Add Item</h3>

            <form action="{% url 'grocerylist:create' %}" method="POST">
                {% csrf_token %}
                <input type="text" name="description" placeholder="New Item">
                <input type="submit" value="Enter">
            </form>

        </div>
    </section>
    
</body>
</html>