code/merritt/21-may/21-may-blog/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('posts.urls')),
]

code/merritt/21-may/21-may-blog/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='home'),
    path('post/<int:pk>/', views.BlogDetailView.as_view(), name='detail'),
    path('post/new/', views.BlogCreateView.as_view(), name='new'),
    path('post/<int:pk>/edit/', views.BlogEditView.as_view(), name='edit'),
    path('post/<int:pk>/delete/', views.BlogDeleteView.as_view(), name='delete'),
]

code/merritt/21-may/21-may-blog/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('<str:username>/', views.UserProfileView.as_view(), name='profile'),
]

code/merritt/21-may/21-may-blog/posts/models.py
from django.db import models
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', args=[self.id])

    class Meta:
        ordering = ['-created']
    

code/merritt/21-may/21-may-blog/posts/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import Post

class BlogListView(ListView):
    model = Post
    template_name = 'home.html'

class BlogDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'

class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'post_new.html'
    fields = ['title', 'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class BlogEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'post_edit.html'
    fields = ['title', 'body']

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

class BlogDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('posts:home')

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

code/merritt/21-may/21-may-blog/users/views.py
from django.views.generic import CreateView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404

class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = 'signup.html'
    success_url = reverse_lazy('login')

class UserProfileView(DetailView):
    model = User
    template_name = 'user_profile.html'
    context_object_name = 'user_profile'
    
    def get_object(self):
        return get_object_or_404(User, username=self.kwargs['username'])

code/merritt/21-may/21-may-blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Super Cool Blog</title>
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond|Libre+Franklin&display=swap" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        <div class="nav-left">
            <h1><a href="{% url 'posts:home' %}">My Super Cool Blog</a></h1>
        </div>
        <div class="nav-right">
            {% if user.is_authenticated %}
            <p>Hello, <a href="{% url 'users:profile' user.username %}">{{ user.username }}</a>!</p>
            <p><a href="{% url 'logout' %}">Logout</a></p>
            <p><a href="{% url 'posts:new' %}">+ New Blog Post</a></p>
            {% else %}
            <p><a href="{% url 'login' %}">Login</a></p>
            <p><a href="{% url 'users:signup' %}">Sign Up</a></p>
            {% endif %}
        </div>
    </header>
    <div class="container">
    {% block content %}
    {% endblock content %}
    </div>
</body>
</html>

code/merritt/21-may/21-may-blog/templates/home.html
{% extends 'base.html' %}

{% block content %}

    {% for post in object_list %}
        <div class="post-entry">
            <h2><a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a></h2>
            <h4><em><a href="{% url 'users:profile' post.author.username %}">{{ post.author.username }}</a></em></h4>
            <p>{{ post.body|linebreaksbr }}</p>
        </div>
    {% endfor %}

{% endblock content %}

code/merritt/21-may/21-may-blog/templates/post_delete.html
{% extends 'base.html' %}

{% block content %}

    <h1>Delete Post</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ post.title }}"?</p>
        <input type="submit" value="Confirm">
    </form>

{% endblock content %}

code/merritt/21-may/21-may-blog/templates/post_detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="post-entry">
        <h2>{{ post.title }}</h2>
        <h4><em><a href="{% url 'users:profile' post.author.username %}">{{ post.author.username }}</a></em></h4>
        <h4><em>Posted on {{ post.created }}</em></h4>
        <h4><em>Last updated on {{ post.updated }}</em></h4>
        <p>{{ post.body|linebreaksbr }}</p>
    </div>

    {% if request.user == post.author %}
    <p><a href="{% url 'posts:edit' post.pk %}">+ Edit Blog Post</a></p>
    <p><a href="{% url 'posts:delete' post.pk %}">+ Delete Blog Post</a></p>
    {% endif %}

{% endblock content %}

code/merritt/21-may/21-may-blog/templates/post_edit.html
{% extends 'base.html' %}

{% block content %}

    <h1>Edit Post</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

{% endblock content %}

code/merritt/21-may/21-may-blog/templates/post_new.html
{% extends 'base.html' %}

{% block content %}

    <h1>New Post</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

{% endblock content %}

code/merritt/21-may/21-may-blog/templates/signup.html
{% extends 'base.html' %}

{% block content %}

    <h1>Sign Up</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Sign up">
    </form>

{% endblock content %}

code/merritt/21-may/21-may-blog/templates/user_profile.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ user_profile.username }}</h1>
    <h5><em>Writing stuff since {{ user_profile.date_joined }}!</em></h5>

    {% for post in user_profile.post_set.all %}
        <div class="post-entry">
            <h2><a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a></h2>
            <h4><em>{{ post.author.username }} -- {{ post.created }}</em></h4>
            <p>{{ post.body|linebreaksbr }}</p>
        </div>
    {% endfor %}

{% endblock content %}