code/merritt/archive/feb-20-grocery/grocery/urls.py
from django.urls import path

from . import views

app_name = 'grocery'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('complete/<int:pk>/', views.complete, name='complete'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

code/merritt/archive/feb-20-grocery/grocery_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('grocery.urls'))
]

code/merritt/archive/feb-20-grocery/grocery/models.py
from django.db import models

class GroceryItem(models.Model):
    description = models.CharField(max_length=200)
    created_date = models.DateTimeField()
    completed_date = models.DateTimeField(null=True, blank=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.description

code/merritt/archive/feb-20-grocery/grocery/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone

from .models import GroceryItem

def index(request):
    incompleted_items = GroceryItem.objects.filter(completed=False).order_by('created_date')
    completed_items = GroceryItem.objects.filter(completed=True).order_by('completed_date')
    context = {
        'incompleted_items': incompleted_items,
        'completed_items': completed_items
    }
    return render(request, 'grocery/index.html', context)

def add(request):
    if request.POST['description']:
        GroceryItem.objects.create(created_date=timezone.now(), description=request.POST['description'])
    return HttpResponseRedirect(reverse('grocery:index'))

def complete(request, pk):
    item = get_object_or_404(GroceryItem, pk=pk)
    if item.completed:
        item.completed = False
        item.completed_date = None
    else:
        item.completed = True
        item.completed_date = timezone.now()
    item.save()
    return HttpResponseRedirect(reverse('grocery:index'))

def delete(request, pk):
    item = get_object_or_404(GroceryItem, pk=pk)
    item.delete()
    return HttpResponseRedirect(reverse('grocery:index'))

code/merritt/archive/feb-20-grocery/grocery/templates/grocery/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>title</title>
    </head>
    <body>
        <h1>Grocery List</h1>

        <form action="{% url 'grocery:add' %}" method="post">
            {% csrf_token %}
            <label for="description">Description:</label>
            <input type="text" id="description" name="description" required>
            <input type="submit" value="Add Grocery Item">
        </form>

        <h2>Incomplete</h2>
        {% for item in incompleted_items %}
            <p>
            {{ item.description }}
            <form action="{% url 'grocery:complete' item.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Complete">
            </form>
            <form action="{% url 'grocery:delete' item.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Delete">
            </form>
            </p>
        {% endfor %}

        <h2>Complete</h2>
        {% for item in completed_items %}
            <p>
            {{ item.description }}
            <form action="{% url 'grocery:complete' item.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Undo">
            </form>
            <form action="{% url 'grocery:delete' item.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Delete">
            </form>
            </p>
        {% endfor %}

    </body>
</html>