code/ollie/django/Lab-01/groceries/urls.py
from django.urls import path

from django.utils import timezone

from . import views

app_name = 'groceries'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete')
]

code/ollie/django/Lab-01/lab01/lab01/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

code/ollie/django/Lab-01/lab01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('groceries/', include('groceries.urls'))
]

code/ollie/django/Lab-01/groceries/models.py
from django.db import models

class GroceryItem(models.Model):
    item_text = models.CharField(max_length=50)
    created_date = models.DateTimeField(auto_now_add=True)
    completed_date = models.DateTimeField(auto_now=True)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return self.item_text

code/ollie/django/Lab-01/groceries/views.py
from django.http import HttpResponseRedirect

from django.urls import reverse

from django.shortcuts import render, get_object_or_404

from .models import GroceryItem

def index(request):
    complete_item = GroceryItem.objects.filter(complete=True)
    incomplete_item = GroceryItem.objects.filter(complete=False)
    context = {
        'complete_item': complete_item,
        'incomplete_item': incomplete_item
    }
    return render(request, 'index.html', context)

def create(request):
    item = request.POST['item_text']
    GroceryItem.objects.create(item_text=item, created_date=GroceryItem.completed_date)
    return HttpResponseRedirect(reverse('groceries:index'))

def update(request, pk):
    item = get_object_or_404(GroceryItem, pk=pk)
    if item.complete:
        item.complete = False
        item.completed_date = None
        item.save()
    else:
        item.complete = True
        item.completed_date = GroceryItem.completed_date
        item.save()
    return HttpResponseRedirect(reverse('groceries:index'))

def delete(request, pk):
    item = get_object_or_404(GroceryItem, pk=pk)
    item.delete()
    return HttpResponseRedirect(reverse('groceries:index'))

code/ollie/django/Lab-01/groceries/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grocery List</title>
</head>
<body>
    <h1>Grocery List</h1>
    <form action="{% url 'groceries:create' %}" method="post">
        {% csrf_token %}
        <input type="text" name="item_text" maxlength="50"/>
        <input type="submit" value="CREATE"/>
    </form>
    <h3>Complete Items</h3>
    <ul>
        {% for item in complete_item %}
        <li>{{ item }}
            <form action="{% url 'groceries:update' item.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" value="COMPLETE">
            </form>
            <form action="{% url 'groceries:delete' item.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" value="DELETE">
            </form>
        </li>
        {% endfor %}
    </ul>
    <h3>Incomplete Items</h3>
    <ul>
        {% for item in incomplete_item %}
        <li>{{ item }}
            <form action="{% url 'groceries:update' item.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" value="INCOMPLETE">
            </form>
            <form action="{% url 'groceries:delete' item.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" value="DELETE">
            </form>
        </li>
        {% endfor %}
    </ul>
</body>
</html>